# Generated by Django 5.1.7 on 2025-03-22 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sermon',
            name='video_url',
        ),
    ]
