# Generated by Django 5.1.6 on 2025-03-31 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0002_remove_sermon_video_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='welcome_images/')),
                ('verse', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
