# Generated by Django 5.1.6 on 2025-03-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('church', '0003_welcomecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='welcome_images/'),
        ),
    ]
